from __future__ import annotations

PRODUCT_DEVELOPMENT = 2
PROJECT_MANAGEMENT = 4
PRODUCT_MANAGEMENT = 30
ACCOUNT_MANAGEMENT = 32
CHAT_BOT = 34
SUPPORTER = 36
CONTRIBUTOR = 42
ALUMNI = 43
PERFORMANCE_COMMITTEE = 44
PROFILE_MINER = 45
BEATMAP_NOMINATION = 53
PREMIUM = 59
SWIMMING_IN_MONEY = 64
FORMER_AKATSUKI_CHAMPION = 66
AKATSUKI_CHAMPION = 67
NINE_INCH_MALES = 69
EVENT_MANAGER = 78
FIVE_PIECE_TENDERS = 80
THREE_GOLDEN_TEACHERS = 83
THE_GOLDEN_GUIDE = 85
SOCIAL_MEDIA_MANAGEMENT = 86
COMMUNITY_MANAGEMENT = 97
TRANSLATOR = 98
COMMUNITY_SUPPORT = 99
NOMINATION_QUALITY_ASSURANCE = 100
PRODUCT_DESIGN = 101
