version: 1
disable_existing_loggers: false
loggers:
  app_logger:
    level: INFO
    handlers: [console]
    propagate: no
  tornado.access:
    level: WARN
    handlers: [console]
    propagate: no
  amplitude:
    level: WARN
    handlers: [console]
    propagate: no
  httpx:
    level: WARN
    handlers: [console]
    propagate: no
  httpcore:
    level: WARN
    handlers: [console]
    propagate: no
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
root:
  level: INFO
  handlers: [console]
