name: production-deploy
on:
  push:
    branches:
      - main
      - AKAT-427-prod-deploy-in-ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy on production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd /home/akatsuki/pep.py
            git pull origin main
            docker build -t bancho-service:latest .
            cd /home/akatsuki/workbench
            docker-compose restart bancho-service
